### ISSUE TITLE
Error when checking out

### ISSUE THREAD

**Issue by Ethan-Hill** [ShoppyGG/shoppy-woocommerce#6]
i get this error when checking out

Error processing checkout. Please try again.

api is correct and secret.

**Comment by AF1QUE** [comment]
Same issue here. @Ethan-Hill Have you found out any solution?

**Comment by YashvirTheCarder** [comment]
Same it doesn't work please fix this or make it without woocommerce.

**Comment by finndev** [comment]
Please make sure you are on the latest version. I have just tested it and everything works fine here.

**Comment by YashvirTheCarder** [comment]
> Please make sure you are on the latest version. I have just tested it and everything works fine here.

oh yeahh its been a while since update, i will update and try it 

hey man just a quick question do you know how hide content until reply for Wordpress ?
Is there any custom shortcodes. 

I tried this [hide hide="reply"]your text here[/hide] 

it works but members (logged in users) who replied to see or replied then refresh website still cannot see hidden content. 

So any idea or custom coding needed to modify to make it work.
Please let me know.

**Comment by bdtipsntricks** [comment]
4th July 2020

Same error on the latest woocommerce and WordPress. Please help
